version: '3.8'

services:
  middle-server:
    build:
      context: ./Middleware
      dockerfile: Dockerfile
    volumes:
      - ./Middleware:/app
    ports:
      - ${MR_PORT_DEV}:8500
      - ${DT_PORT_DEV}:8501

networks:
  default:
    attachable: true
